
buildscript {

    ext.propsFile = new File(rootDir.getParent(), 'samples.properties')
    apply from: propsFile

    repositories {
        mavenCentral()
    }
    dependencies {
	 classpath("org.springframework.boot:spring-boot-gradle-plugin:" + boot4Version)
    }
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'

// The local, flatDir configuration lets us use a modified version from
// this repository without needing it released via maven
repositories {
  flatDir() {
    dirs '../../mq-jms-spring-boot-starter'
  }
  mavenCentral()
  mavenLocal()
}

// The Atomikos module is no longer provided with Spring. But we can still get it directly
dependencies {
  implementation("com.ibm.mq:mq-jms-spring-boot-starter:" + mqBoot4StarterVersion)
  implementation("com.atomikos:transactions-spring-boot4-starter:6.0.1") 
}

// Some atomikos features are controlled by -D Java properties. They can be
// set here as the Spring Boot processing might be too late
bootRun {
  systemProperty('com.atomikos.icatch.xxxxxxxxxx','true')
}

