
buildscript {
    ext.propsFile = new File(rootDir.getParent(), 'samples.properties')
    apply from: propsFile

    repositories {
        mavenCentral()
    }
    dependencies {
	 classpath("org.springframework.boot:spring-boot-gradle-plugin:" + boot4Version)
    }
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'

// The local, flatDir configuration lets us use a modified version from
// this repository without needing it released via maven
repositories {
  flatDir() {
    dirs '../../mq-jms-spring-boot-starter'
  }
  mavenCentral()
  mavenLocal()

}

dependencies {
  implementation("com.ibm.mq:mq-jms-spring-boot-starter:" + mqBoot4StarterVersion)
  implementation("dev.snowdrop:narayana-spring-boot-starter:" + narayanaVersion)
}

