ext {
  // Which version of Spring Boot are we using
  boot3Version = '3.5.15'
  boot4Version = '4.0.7'

  // These will usually be the same as the corresponding Spring Boot version but might not be
  mqBoot3StarterVersion = '3.5.15'
  mqBoot4StarterVersion = '4.0.7'

  // Versions of any other dependencies in the samples
  narayanaVersion = '4.0.0'
  atomikosVersion = '6.0.1'
}

println("Using samples.properties")
